name: Schedule Push TikTok

on:
  schedule:
    - cron: '0 */6 * * *' # Chạy mỗi 6 tiếng
  push:
    branches:
      - main # Chạy khi có push lên nhánh main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Push_TikTok script
      run: |
        python Push_TikTok.py
